#Create READ-ONLY user
--CREATE USER
CREATE USER USER_NAME IDENTIFIED BY "PASSWD"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
/

--SYS GRANTS
GRANT CREATE SESSION TO USER_NAME;

--READ-ONLY-GRANT via rols
GRANT "ROLENAME" TO USER_NAME;

-- --READ-ONLY-Object Grants

--TS Quotas

